name: Build
on: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Generate xml from md with mmark
        run: ./bin/mmark assets/main.md > output.xml
