name: Build
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install mmark
        run: ./scripts/install_mmark.sh 

      - name: Install Xml2Rfc
        run: apt-get install -y xml2rfc

      - name: Generate xml for RFC
        run: bin/mmarkmmark template/main.md > output/spec.xml

      - name: Generate final output
        run: xml2rfc output/spec.xml --v3 --html --pdf --text
        
