name: Build
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install mmark
        run: ./scripts/install_mmark.sh 
         

      - name: Install Xml2Rfc
        run: apt-get install -y xml2rfc

      - name: Generate xml
        run: bin/mmark template/main.md > temp/spec.xml
        
